server:
  port: 8085
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Guino-Elvis/BACK_MOBIL_DJF.git
          search-paths: config-data
          default-label: main
  security:
    user:
      name: root
      password: s3cr3t
  
